# Generated by Django 6.0.2 on 2026-04-19 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(choices=[('PHP Full Stack Web Development', 'PHP Full Stack Web Development'), ('Python Full Stack Web Development', 'Python Full Stack Web Development'), ('Java Full Stack Web Development', 'Java Full Stack Web Development'), ('MERN Stack Development', 'MERN Stack Development'), ('MEAN Stack Development', 'MEAN Stack Development'), ('Data Analytics', 'Data Analytics'), ('Cloud Computing', 'Cloud Computing'), ('Artificial Intelligence / Machine Learning', 'Artificial Intelligence / Machine Learning')], max_length=200)),
                ('question_text', models.TextField()),
                ('option_a', models.CharField(max_length=500)),
                ('option_b', models.CharField(max_length=500)),
                ('option_c', models.CharField(max_length=500)),
                ('option_d', models.CharField(max_length=500)),
                ('correct_answer', models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=200)),
                ('domain', models.CharField(choices=[('PHP Full Stack Web Development', 'PHP Full Stack Web Development'), ('Python Full Stack Web Development', 'Python Full Stack Web Development'), ('Java Full Stack Web Development', 'Java Full Stack Web Development'), ('MERN Stack Development', 'MERN Stack Development'), ('MEAN Stack Development', 'MEAN Stack Development'), ('Data Analytics', 'Data Analytics'), ('Cloud Computing', 'Cloud Computing'), ('Artificial Intelligence / Machine Learning', 'Artificial Intelligence / Machine Learning')], max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_questions', models.IntegerField()),
                ('correct_answers', models.IntegerField()),
                ('wrong_answers', models.IntegerField()),
                ('score', models.IntegerField()),
                ('exam_date', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D')], max_length=1)),
                ('is_correct', models.BooleanField(default=False)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.student')),
            ],
        ),
    ]
