# Generated by Django 6.0.4 on 2026-04-20 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_alter_studentanswer_is_correct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='unanswered_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='score',
            field=models.FloatField(),
        ),
    ]
